using Terraria.Audio;

namespace CalamityOverhaul.Common
{
    [VaultLoaden(CWRConstant.Asset + "Sounds")]
    public static class CWRSound
    {
        public static SoundStyle loadTheRounds;
        public static SoundStyle MeatySlash;
        public static SoundStyle SwiftSlice;
        public static SoundStyle Pecharge;
        public static SoundStyle Peuncharge = new SoundStyle(CWRConstant.Asset + "Sounds/Peuncharge");
        public static SoundStyle BlackHole;
        public static SoundStyle Accumulator;
        public static SoundStyle Bees;
        public static SoundStyle BlankGun;
        public static SoundStyle Case;
        public static SoundStyle CaseEjection;
        public static SoundStyle CaseEjection2;
        public static SoundStyle Ejection;
        public static SoundStyle Liquids_Fill_0;
        public static SoundStyle EndSilkOrbSpanSound;
        public static SoundStyle ShurikenOut;
        public static SoundStyle Retracting;
        public static SoundStyle HitTheFlesh_1;
        public static SoundStyle HitTheFlesh_2;
        public static SoundStyle HitTheSteel;
        public static SoundStyle V_Kengms;
        public static SoundStyle V_ThisThePwero;
        public static SoundStyle V_TOEeys = new SoundStyle(CWRConstant.Asset + "Sounds/EasterEggSound/V_TOEeys");
        public static SoundStyle V_YouSouDiad;
        public static SoundStyle V_Dead;
        public static SoundStyle V_Heen;
        public static SoundStyle V_Hooaaa;
        public static SoundStyle V_You_Wo_Namges_Is_The_Pwero;
        public static SoundStyle DeploymentSound;
        public static SoundStyle DeploymentSound_Fire;
        public static SoundStyle DeploymentSound_AP;
        public static SoundStyle MechanicalFullBloodFlow;
        public static SoundStyle SpawnArmMgs;
        public static SoundStyle Gun_50CAL_Shoot;
        public static SoundStyle Gun_AUTO_Shoot;
        public static SoundStyle Gun_AWP_Shoot;
        public static SoundStyle Gun_MP5_Shoot;
        public static SoundStyle Gun_PISTOL_Shoot;
        public static SoundStyle Gun_SMG_Shoot;
        public static SoundStyle Gun_Shotgun_LoadShell;
        public static SoundStyle Gun_Shotgun_Pump;
        public static SoundStyle Gun_Shotgun_Shoot;
        public static SoundStyle Gun_Shotgun_Shoot2;
        public static SoundStyle Gun_HandGun_ClipLocked;
        public static SoundStyle Gun_HandGun_ClipOut;
        public static SoundStyle Gun_HandGun_SlideInShoot;
        public static SoundStyle Gun_Clipin;
        public static SoundStyle Gun_ClipIn1;
        public static SoundStyle Gun_ClipinLocked;
        public static SoundStyle Gun_Clipout;
        public static SoundStyle Gun_Slideforward1;
        public static SoundStyle Gun_SportingGun_Shoot;
        public static SoundStyle Gun_Musket_ClipOut;
        public static SoundStyle Gun_Snowblindness_Shoot;
        public static SoundStyle Gun_Crossbow_Shoot;
        public static SoundStyle Gun_Slingshot_Shoot;
        public static SoundStyle Gun_Snowblindness_Clipin;
        public static SoundStyle Gun_Snowblindness_Clipout;
        public static SoundStyle Gun_Magnum_Shoot;
        public static SoundStyle Gun_Magnum_ClipLocked = new SoundStyle(CWRConstant.Asset + "Sounds/Gun/Magnum_ClipLocked");
        public static SoundStyle Gun_Magnum_ClipOut = new SoundStyle(CWRConstant.Asset + "Sounds/Gun/Magnum_ClipOut");
        public static SoundStyle Gun_Rifle_Shoot = new SoundStyle(CWRConstant.Asset + "Sounds/Gun/Rifle_Shoot");
        public static SoundStyle Gun_BoltAction = new SoundStyle(CWRConstant.Asset + "Sounds/Gun/BoltAction");
        public static SoundStyle Gun_NERifle_ClipLocked = new SoundStyle(CWRConstant.Asset + "Sounds/Gun/NERifle_ClipLocked");
        public static SoundStyle Gun_NERifle_SlideInt = new SoundStyle(CWRConstant.Asset + "Sounds/Gun/NERifle_SlideInt");
        public static SoundStyle Bow_Shoot = new SoundStyle(CWRConstant.Asset + "Sounds/Bow/Bow_Shoot");
        public static SoundStyle Bow_String = new SoundStyle(CWRConstant.Asset + "Sounds/Bow/Bow_String");
        public static SoundStyle JustStrike = new SoundStyle(CWRConstant.Asset + "Sounds/JustStrike");
        public static SoundStyle Dash = new SoundStyle(CWRConstant.Asset + "Sounds/Dash");
        public static SoundStyle Windmill = new SoundStyle(CWRConstant.Asset + "Sounds/Windmill");
        public static SoundStyle TeslaOpen = new SoundStyle(CWRConstant.Asset + "Sounds/TeslaOpen");
        public static SoundStyle MagneticBurst = new SoundStyle(CWRConstant.Asset + "Sounds/MagneticBurst");
        public static SoundStyle ArcCharging = new SoundStyle(CWRConstant.Asset + "Sounds/ArcCharging");
        public static SoundStyle CollectorStart = new SoundStyle(CWRConstant.Asset + "Sounds/CollectorStart");
        public static SoundStyle Select = new SoundStyle(CWRConstant.Asset + "Sounds/Select");
        public static SoundStyle RollingMERoer = new SoundStyle(CWRConstant.Asset + "Sounds/RollingMERoer");
        public static SoundStyle SporeBubble = new SoundStyle(CWRConstant.Asset + "Sounds/SporeBubble");
        public static SoundStyle PutSaddle = new SoundStyle(CWRConstant.Asset + "Sounds/PutSaddle");
        public static SoundStyle ButtonZero = new SoundStyle(CWRConstant.Asset + "Sounds/ButtonZero");
        public static SoundStyle ToMount = new SoundStyle(CWRConstant.Asset + "Sounds/ToMount");
        public static SoundStyle Hajm = new SoundStyle(CWRConstant.Asset + "Sounds/Hajm");
        public static SoundStyle None = new SoundStyle(CWRConstant.Asset + "Sounds/None");
        public static SoundStyle OldDuchestClose = new SoundStyle(CWRConstant.Asset + "Sounds/OldDuchestClose");
        public static SoundStyle OldDuchestOpen = new SoundStyle(CWRConstant.Asset + "Sounds/OldDuchestOpen");
        public static SoundStyle Rollout = new SoundStyle(CWRConstant.Asset + "Sounds/Rollout");
        public static SoundStyle INeedMorePower = new SoundStyle(CWRConstant.Asset + "Sounds/INeedMorePower");
        public static SoundStyle Thunder = new SoundStyle(CWRConstant.Asset + "Sounds/Thunder");
        public static SoundStyle SandevistanEnd = new SoundStyle(CWRConstant.Asset + "Sounds/SandevistanEnd");
        public static SoundStyle SandevistanStart = new SoundStyle(CWRConstant.Asset + "Sounds/SandevistanStart");
        public static SoundStyle FailureCurrent;
        public static SoundStyle Fault;
        public static SoundStyle FaultOccurred;
        public static SoundStyle Faultrelease;
        public static SoundStyle FaultTransition;
        public static SoundStyle Hacker;
        public static SoundStyle Scanning;
    }
}
